import * as fs from "fs";
import * as chalk from "chalk";
import * as path from "path";
import * as childProcess from "child_process";
import { coerce, compare, gte, valid } from "semver";
import { downloadBlob, extractArchive, fileDoesNotExistOrIsDirectory, fileExists } from "./utils/file-utils";
import { evaluateKotlinDslReactConfig, resolveGradleBuildFile } from "./utils/gradle-utils";
import * as dotenv from "dotenv";
import { DotenvParseOutput } from "dotenv";
import * as cli from "../script/types/cli";
import { log, sdk } from "./command-executor";

const g2js = require("gradle-to-js/lib/parser");

export function isValidVersion(version: string): boolean {
  return !!valid(version) || /^\d+\.\d+$/.test(version);
}

export async function getBundleSourceMapOutput(command: cli.IReleaseReactCommand, bundleName: string, sourcemapOutputFolder: string) {
  let bundleSourceMapOutput: string | undefined;
  switch (command.platform) {
    case "android": {
      // see BundleHermesCTask -> resolvePackagerSourceMapFile
      // for Hermes targeted bundles there are 2 source maps: "packager" (metro) and "compiler" (Hermes)
      // Metro bundles use <bundleAssetName>.packager.map notation
      const isHermes = await isHermesEnabled(command, command.platform);
      if (isHermes) {
        bundleSourceMapOutput = path.join(sourcemapOutputFolder, bundleName + ".packager.map");
      } else {
        bundleSourceMapOutput = path.join(sourcemapOutputFolder, bundleName + ".map");
      }

      break;
    }
    case "ios": {
      // see react-native-xcode.sh
      // to match js bundle generated by Xcode and by Revopush cli we must respect SOURCEMAP_FILE value
      // because it appears as //# sourceMappingURL value in a js bundle
      const xcodeDotEnvValue = getXcodeDotEnvValue("SOURCEMAP_FILE");
      const sourceMapFilename = xcodeDotEnvValue ? path.basename(xcodeDotEnvValue) : bundleName + ".map";

      bundleSourceMapOutput = path.join(sourcemapOutputFolder, sourceMapFilename);

      break;
    }
    default:
      throw new Error('Platform must be either "android" or "ios".');
  }
  return bundleSourceMapOutput;
}

export async function takeHermesBaseBytecode(
  command: cli.IReleaseReactCommand,
  baseReleaseTmpFolder: string,
  outputFolder: string,
  bundleName: string
): Promise<string | null> {
  const { bundleBlobUrl } = await sdk.getBaseRelease(command.appName, command.deploymentName, command.appStoreVersion, command.buildNumber);
  if (!bundleBlobUrl) {
    return null;
  }

  const baseReleaseArchive = await downloadBlob(bundleBlobUrl, baseReleaseTmpFolder);
  await extractArchive(baseReleaseArchive, baseReleaseTmpFolder);
  const baseReleaseBundle = path.join(baseReleaseTmpFolder, path.basename(outputFolder), bundleName);

  if (!fs.existsSync(baseReleaseBundle)) {
    log(chalk.cyan("\nNo base release available...\n"));
    return null;
  }

  return baseReleaseBundle;
}

// Hermes BytecodeFileHeader: uint64 magic, uint32 version (little-endian), stable since Hermes v0.1
const HERMES_BYTECODE_MAGIC = BigInt("0x1F1903C103BC1FC6");

function getHermesBytecodeVersion(bytecode: Buffer): number | null {
  if (bytecode.length < 12 || bytecode.readBigUInt64LE(0) !== HERMES_BYTECODE_MAGIC) {
    return null;
  }
  return bytecode.readUInt32LE(8);
}

// Compile an empty input to stdout and read the version from the emitted header
export function getHermesCompilerBytecodeVersion(hermesCommand: string): number | null {
  const result = childProcess.spawnSync(hermesCommand, ["-emit-binary", "-"], { input: "", timeout: 30000 });
  return result.status === 0 ? getHermesBytecodeVersion(result.stdout) : null;
}

// hermesc -base-bytecode aborts on a base of another bytecode version; the base is only a diff optimization
export function resolveHermesBaseBytecode(baseBytecode: string, compilerBytecodeVersion: number | null): string | null {
  const baseBytecodeVersion = getHermesBytecodeVersion(fs.readFileSync(baseBytecode));
  if (baseBytecodeVersion === null) {
    log(chalk.yellow("\nBase release bundle is not Hermes bytecode, skipping -base-bytecode.\n"));
    return null;
  }

  if (compilerBytecodeVersion === null) {
    log(chalk.yellow("\nCould not detect the Hermes compiler bytecode version, skipping -base-bytecode.\n"));
    return null;
  }

  if (baseBytecodeVersion !== compilerBytecodeVersion) {
    log(
      chalk.yellow(
        `\nWarning: base release is Hermes bytecode v${baseBytecodeVersion}, local compiler produces v${compilerBytecodeVersion}. ` +
          `Skipping -base-bytecode. Binaries on v${baseBytecodeVersion} can't run this update.\n`
      )
    );
    return null;
  }

  return baseBytecode;
}

export async function runHermesEmitBinaryCommand(
  command: cli.IReleaseReactCommand,
  bundleName: string,
  outputFolder: string,
  sourcemapOutputFolder: string,
  extraHermesFlags: string[],
  gradleFile: string,
  baseBytecode?: string
): Promise<void> {
  const hermesArgs: string[] = [];
  const envNodeArgs: string = process.env.CODE_PUSH_NODE_ARGS;

  if (typeof envNodeArgs !== "undefined") {
    Array.prototype.push.apply(hermesArgs, envNodeArgs.trim().split(/\s+/));
  }

  Array.prototype.push.apply(hermesArgs, [
    "-emit-binary",
    "-O",
    "-out",
    path.join(outputFolder, bundleName + ".hbc"),
    path.join(outputFolder, bundleName),
    "-w",
    "-max-diagnostic-width=80",
    ...extraHermesFlags,
  ]);

  if (sourcemapOutputFolder) {
    hermesArgs.push("-output-source-map");
  }

  const hermesCommand = await getHermesCommand(command.platform, gradleFile, command.podFile);

  if (baseBytecode) {
    const compilerBytecodeVersion = getHermesCompilerBytecodeVersion(hermesCommand);
    const resolvedBaseBytecode = resolveHermesBaseBytecode(baseBytecode, compilerBytecodeVersion);
    if (resolvedBaseBytecode) {
      hermesArgs.push("-base-bytecode", resolvedBaseBytecode);
    }
  }

  console.log(chalk.cyan("Converting JS bundle to byte code via Hermes, running command:\n"));
  const hermesProcess = childProcess.spawn(hermesCommand, hermesArgs);
  console.log(`${hermesCommand} ${hermesArgs.join(" ")}`);

  return new Promise<void>((resolve, reject) => {
    hermesProcess.on("error", reject);

    hermesProcess.stdout.on("data", (data: Buffer) => {
      console.log(data.toString().trim());
    });

    hermesProcess.stderr.on("data", (data: Buffer) => {
      console.error(data.toString().trim());
    });

    hermesProcess.on("close", (exitCode: number, signal: string) => {
      if (exitCode !== 0) {
        reject(new Error(`"hermes" command failed (exitCode=${exitCode}, signal=${signal}).`));
        return;
      }
      // Copy HBC bundle to overwrite JS bundle
      const source = path.join(outputFolder, bundleName + ".hbc");
      const destination = path.join(outputFolder, bundleName);
      fs.copyFile(source, destination, (err) => {
        if (err) {
          console.error(err);
          reject(new Error(`Copying file ${source} to ${destination} failed. "hermes" previously exited with code ${exitCode}.`));
          return;
        }
        fs.unlink(source, (err) => {
          if (err) {
            console.error(err);
            reject(err);
            return;
          }
          resolve(null as void);
        });
      });
    });
  }).then(async () => {
    if (!sourcemapOutputFolder) {
      // skip source map compose if source map is not enabled
      return;
    }

    const composeSourceMapsPath = getComposeSourceMapsPath();
    if (!composeSourceMapsPath) {
      throw new Error("react-native compose-source-maps.js scripts is not found");
    }

    const jsCompilerSourceMapFile = path.join(outputFolder, bundleName + ".hbc" + ".map");
    if (!fs.existsSync(jsCompilerSourceMapFile)) {
      throw new Error(`sourcemap file ${jsCompilerSourceMapFile} is not found`);
    }

    const platformSourceMapOutput = await getBundleSourceMapOutput(command, bundleName, sourcemapOutputFolder);
    return new Promise((resolve, reject) => {
      let bundleSourceMapOutput = sourcemapOutputFolder;
      let combinedSourceMapOutput = sourcemapOutputFolder;

      if (!sourcemapOutputFolder.endsWith(".map")) {
        bundleSourceMapOutput = platformSourceMapOutput;
        switch (command.platform) {
          case "android": {
            combinedSourceMapOutput = path.join(sourcemapOutputFolder, bundleName + ".map");
            break;
          }
          case "ios": {
            combinedSourceMapOutput = bundleSourceMapOutput;
            break;
          }
          default:
            throw new Error('Platform must be either "android" or "ios".');
        }
      }
      const composeSourceMapsArgs = [
        composeSourceMapsPath,
        bundleSourceMapOutput,
        jsCompilerSourceMapFile,
        "-o",
        combinedSourceMapOutput,
      ];

      // https://github.com/facebook/react-native/blob/master/react.gradle#L211
      // https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh#L178
      // packager.sourcemap.map + hbc.sourcemap.map = sourcemap.map
      const composeSourceMapsProcess = childProcess.spawn("node", composeSourceMapsArgs);
      console.log(`${composeSourceMapsPath} ${composeSourceMapsArgs.join(" ")}`);

      composeSourceMapsProcess.stdout.on("data", (data: Buffer) => {
        console.log(data.toString().trim());
      });

      composeSourceMapsProcess.stderr.on("data", (data: Buffer) => {
        console.error(data.toString().trim());
      });

      composeSourceMapsProcess.on("close", (exitCode: number, signal: string) => {
        if (exitCode !== 0) {
          reject(new Error(`"compose-source-maps" command failed (exitCode=${exitCode}, signal=${signal}).`));
          return;
        }

        // Delete the HBC sourceMap, otherwise it will be included in 'code-push' bundle as well
        fs.unlink(jsCompilerSourceMapFile, (err) => {
          if (err) {
            console.error(err);
            reject(err);
            return;
          }

          resolve(null);
        });
      });
    });
  });
}

export function getXcodeDotEnvValue(key: string): string | undefined {
  // Xcode sources .xcode.env, then .xcode.env.local
  const xcodeEnvs = loadEnvAsMap([path.join("ios", ".xcode.env"), path.join("ios", ".xcode.env.local")]);
  return xcodeEnvs.get(key);
}

export async function getMinifyParams(command: cli.IReleaseReactCommand) {
  const isHermes = await isHermesEnabled(command);

  switch (command.platform) {
    case "android": {
      // android always explicitly pass --minify true/false
      // TaskConfiguration        it.minifyEnabled.set(!isHermesEnabledInThisVariant)
      return ["--minify", !isHermes];
    }
    case "ios": {
      //if [[ $USE_HERMES != false && $DEV == false ]]; then
      //   EXTRA_ARGS+=("--minify" "false")
      // fi
      // ios does pass --minify false only if Hermes enables and does pass anything otherwise
      return isHermes ? ["--minify", false] : [];
    }
    default:
      throw new Error('Platform must be either "android" or "ios".');
  }
}

export async function isHermesEnabled(command: cli.IReleaseReactCommand, platform: string = command.platform.toLowerCase()) {
  if (command.useHermes) return true;
  if (platform === "android") return getAndroidHermesEnabled(command.gradleFile);
  if (platform === "ios") return getiOSHermesEnabled(command.podFile);
  return false;
}

function parseBuildGradleFile(gradleFile: string) {
  let buildGradlePath: string = path.join("android", "app");
  if (gradleFile) {
    buildGradlePath = gradleFile;
  }

  try {
    if (fs.lstatSync(buildGradlePath).isDirectory()) {
      buildGradlePath = path.join(buildGradlePath, "build.gradle");
      fs.accessSync(buildGradlePath);
    }
  } catch {
    throw new Error(`Unable to find gradle file "${buildGradlePath}".`);
  }

  return g2js.parseFile(buildGradlePath).catch(() => {
    throw new Error(`Unable to parse the "${buildGradlePath}" file. Please ensure it is a well-formed Gradle file.`);
  });
}

function parseGradlePropertiesFile(gradleFile: string): Record<string, string> {
  let gradlePropsPath: string = path.join("android", "gradle.properties");

  try {
    if (gradleFile) {
      const base = gradleFile;
      const stat = fs.lstatSync(base);

      if (stat.isDirectory()) {
        if (path.basename(base) === "app") {
          gradlePropsPath = path.join(base, "..", "gradle.properties");
        } else {
          gradlePropsPath = path.join(base, "gradle.properties");
        }
      } else {
        gradlePropsPath = path.join(path.dirname(base), "..", "gradle.properties");
      }
    }
  } catch {}

  gradlePropsPath = path.normalize(gradlePropsPath);

  if (fileDoesNotExistOrIsDirectory(gradlePropsPath)) {
    throw new Error(`Unable to find gradle.properties file "${gradlePropsPath}".`);
  }

  const text = fs.readFileSync(gradlePropsPath, "utf8");
  const props: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const m = line.match(/^([^=\s]+)\s*=\s*(.*)$/);
    if (m) {
      const key = m[1].trim();
      const val = m[2].trim();
      props[key] = val;
    }
  }
  return props;
}

// Only literal paths (plus $rootDir / $projectDir) can be resolved; other Groovy expressions, like Expo's, are ignored
async function getHermesCommandFromGradle(gradleFile: string): Promise<string> {
  const buildFile = resolveGradleBuildFile(gradleFile || path.join("android", "app"));
  if (buildFile.endsWith(".kts")) {
    return getHermesCommandFromKotlinDsl(buildFile);
  }

  const buildGradle: any = await parseBuildGradleFile(gradleFile);
  const gradlePath = gradleFile || path.join("android", "app");
  const appDir = path.resolve(directoryExistsSync(gradlePath) ? gradlePath : path.dirname(gradlePath));
  const rootDir = path.dirname(appDir);

  // The gradle plugin runs hermesc from react.root (default: $rootDir/..); legacy react.gradle from the app module
  let hermesCommand: string = buildGradle.react?.hermesCommand;
  let workingDir = path.dirname(rootDir);
  if (!hermesCommand) {
    const legacyProperties: string[] = Array.from(buildGradle["project.ext.react"] || []);
    const legacyProperty = legacyProperties.find((prop) => prop.trim().startsWith("hermesCommand:"));
    hermesCommand = legacyProperty?.replace("hermesCommand:", "").trim().slice(1, -1);
    workingDir = appDir;
  }
  if (!hermesCommand) {
    return "";
  }

  hermesCommand = hermesCommand
    .replace(/\$(\{rootDir\}|rootDir\b)/g, () => rootDir)
    .replace(/\$(\{projectDir\}|projectDir\b)/g, () => appDir);
  if (/["'$()+]/.test(hermesCommand)) {
    return "";
  }

  return path.resolve(workingDir, hermesCommand.replace("%OS-BIN%", getHermesOSBin()));
}

// Kotlin DSL can't be parsed statically, so evaluate it with Gradle, but only if it sets hermesCommand
async function getHermesCommandFromKotlinDsl(buildFile: string): Promise<string> {
  if (!/^\s*(react\.)?hermesCommand\b/m.test(fs.readFileSync(buildFile, "utf8"))) {
    return "";
  }

  try {
    const { hermesCommand, root } = await evaluateKotlinDslReactConfig(buildFile);
    return hermesCommand && root ? path.resolve(root, hermesCommand.replace("%OS-BIN%", getHermesOSBin())) : "";
  } catch (error) {
    log(chalk.yellow(`\nWarning: ${error.message}\nUsing the default hermesc instead.\n`));
    return "";
  }
}

function isHermesV1EnabledInGradle(gradleFile: string): boolean {
  try {
    return parseGradlePropertiesFile(gradleFile).hermesV1Enabled?.toLowerCase() === "true";
  } catch {
    return false;
  }
}

async function getAndroidHermesEnabled(gradleFile: string): Promise<boolean> {
  try {
    const props = parseGradlePropertiesFile(gradleFile);
    if (typeof props.hermesEnabled !== "undefined") {
      const v = String(props.hermesEnabled).trim().toLowerCase();
      if (v === "true") return true;
      if (v === "false") return false;
    }
  } catch {}

  try {
    const buildGradle: any = await parseBuildGradleFile(gradleFile);
    const lines: string[] = Array.from(buildGradle["project.ext.react"] || []);
    if (lines.some((l) => /\benableHermes\s*:\s*true\b/.test(l))) return true;
    if (lines.some((l) => /\benableHermes\s*:\s*false\b/.test(l))) return false;
  } catch {}

  const rnVersion = coerce(getReactNativeVersion())?.version;
  return rnVersion && compare(rnVersion, "0.70.0") >= 0;
}

function getiOSHermesEnabled(podFile: string): boolean {
  const podPath = podFile || path.join("ios", "Podfile");
  if (podFile && fileDoesNotExistOrIsDirectory(podPath)) {
    throw new Error(`Unable to find Podfile file "${podPath}".`);
  } else if (!podFile && fileDoesNotExistOrIsDirectory(podPath)) {
    // No Podfile at default path (e.g. Android-only project); fall back to RN version heuristic
    const rnVersion = coerce(getReactNativeVersion())?.version;
    return !!(rnVersion && compare(rnVersion, "0.70.0") >= 0);
  }

  try {
    const podFileContents = fs.readFileSync(podPath).toString();

    const hasTrue = /([^#\n]*:?hermes_enabled(\s+|\n+)?(=>|:)(\s+|\n+)?true)/.test(podFileContents);
    if (hasTrue) return true;

    const hasFalse = /([^#\n]*:?hermes_enabled(\s+|\n+)?(=>|:)(\s+|\n+)?false)/.test(podFileContents);
    if (hasFalse) return false;

    const rnVersion = coerce(getReactNativeVersion())?.version;
    return rnVersion && compare(rnVersion, "0.70.0") >= 0;
  } catch (error) {
    throw error;
  }
}

function loadEnvAsMap(envPaths = []): Map<string, string | undefined> {
  const merged: DotenvParseOutput = {};

  for (const envPath of envPaths) {
    if (fs.existsSync(envPath)) {
      Object.assign(merged, dotenv.parse(fs.readFileSync(envPath))); // later files override earlier ones
    }
  }

  // fallback to process.env for anything missing
  return new Map([...Object.entries(process.env), ...Object.entries(merged)]);
}

function getHermesOSBin(): string {
  switch (process.platform) {
    case "win32":
      return "win64-bin";
    case "darwin":
      return "osx-bin";
    case "freebsd":
    case "linux":
    case "sunos":
    default:
      return "linux64-bin";
  }
}

function getHermesOSExe(): string {
  const react63orAbove = compare(coerce(getReactNativeVersion())?.version, "0.63.0") !== -1;
  const hermesExecutableName = react63orAbove ? "hermesc" : "hermes";
  switch (process.platform) {
    case "win32":
      return hermesExecutableName + ".exe";
    default:
      return hermesExecutableName;
  }
}

// Mirrors how React Native picks hermesc, so updates are compiled like the store binary.
// Android: gradle-plugin PathUtils.detectOSAwareHermesCommand; iOS: scripts/react-native-xcode.sh
export async function getHermesCommand(platform: string, gradleFile: string, podFile: string): Promise<string> {
  const reactNativePath = getReactNativePackagePath();
  const bundledHermesc = path.join(reactNativePath, "sdks", "hermesc", getHermesOSBin(), getHermesOSExe());
  const hermesCompiler = getHermesCompilerPath(reactNativePath);
  let candidates: string[];

  if (platform === "ios") {
    // react-native-xcode.sh honors HERMES_CLI_PATH from the environment or ios/.xcode.env(.local)
    const hermesCliPath = getXcodeDotEnvValue("HERMES_CLI_PATH");
    if (hermesCliPath) {
      return hermesCliPath;
    }
    const podsDir = path.join(path.dirname(podFile || path.join("ios", "Podfile")), "Pods");
    const podsHermesc = path.join(podsDir, "hermes-engine", "destroot", "bin", "hermesc");

    // Without Pods (e.g. CI), pick the compiler like Android: RN 0.82 uses hermes-compiler only for Hermes V1
    if (process.env.RCT_HERMES_V1_ENABLED === "1") {
      candidates = [podsHermesc, hermesCompiler, bundledHermesc];
    } else {
      candidates = [podsHermesc, bundledHermesc, hermesCompiler];
    }
  } else {
    // A missing or unparsable gradle file just means there is no hermesCommand override
    const gradleHermesCommand = await getHermesCommandFromGradle(gradleFile).catch(() => "");
    if (gradleHermesCommand) {
      return gradleHermesCommand;
    }

    const overrideHermesDir = process.env.REACT_NATIVE_OVERRIDE_HERMES_DIR;
    const sourceBuiltHermesc = overrideHermesDir
      ? path.join(overrideHermesDir, "build", "bin", getHermesOSExe())
      : path.join(reactNativePath, "ReactAndroid", "hermes-engine", "build", "hermes", "bin", getHermesOSExe());

    // RN 0.82 uses hermes-compiler only with hermesV1Enabled; RN <= 0.82 ships sdks/hermesc, RN 0.83+ only hermes-compiler
    if (isHermesV1EnabledInGradle(gradleFile)) {
      candidates = [sourceBuiltHermesc, hermesCompiler, bundledHermesc];
    } else {
      candidates = [sourceBuiltHermesc, bundledHermesc, hermesCompiler];
    }
  }

  // RN < 0.69 shipped hermesc in the hermes-engine / hermesvm packages
  const nodeModulesPath = getNodeModulesPath(reactNativePath);
  candidates.push(path.join(nodeModulesPath, "hermes-engine", getHermesOSBin(), getHermesOSExe()));

  const hermesc = candidates.find((candidate) => candidate && fileExists(candidate));
  return hermesc || path.join(nodeModulesPath, "hermesvm", getHermesOSBin(), "hermes");
}

// hermes-compiler is a dependency of react-native, so resolve it from there (it may not be hoisted)
function getHermesCompilerPath(reactNativePath: string): string | null {
  try {
    const packageJson = require.resolve("hermes-compiler/package.json", { paths: [reactNativePath] });
    return path.join(path.dirname(packageJson), "hermesc", getHermesOSBin(), getHermesOSExe());
  } catch {
    return null;
  }
}

function getComposeSourceMapsPath(): string {
  // detect if compose-source-maps.js script exists
  const composeSourceMaps = path.join(getReactNativePackagePath(), "scripts", "compose-source-maps.js");
  if (fs.existsSync(composeSourceMaps)) {
    return composeSourceMaps;
  }
  return null;
}

function getNodeModulesPath(reactNativePath: string): string {
  const nodeModulesPath = path.dirname(reactNativePath);
  if (directoryExistsSync(nodeModulesPath)) {
    return nodeModulesPath;
  }

  return path.join("node_modules");
}

export function getReactNativePackagePath(): string {
  const result = childProcess.spawnSync("node", ["--print", "require.resolve('react-native/package.json')"]);
  const packagePath = path.dirname(result.stdout.toString());
  if (result.status === 0 && directoryExistsSync(packagePath)) {
    return packagePath;
  }

  return path.join("node_modules", "react-native");
}

export function directoryExistsSync(dirname: string): boolean {
  try {
    return fs.statSync(dirname).isDirectory();
  } catch (err) {
    if (err.code !== "ENOENT") {
      throw err;
    }
  }
  return false;
}

export function getReactNativeVersion(): string {
  try {
    const result = childProcess.spawnSync("node", ["--print", "require('react-native/package.json').version"]);
    return result.stdout.toString().trim();
  } catch (error) {
    throw new Error(
      'Unable to resolve "react-native". Please make sure it is installed in your project (e.g. "npm install react-native").'
    );
  }
}
